name: Tests

on:
  push:
    branches: ["develop", "release-*"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
      - run: pip install tox
      - run: tox -e tests